# Generated by Django 4.2 on 2023-04-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="location_id",
            new_name="location",
        ),
    ]
