# Generated by Django 4.2 on 2023-05-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_age_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Пользователь"),
                    ("moderator", "Модератор"),
                    ("admin", "Админ"),
                ],
                default="member",
                max_length=9,
            ),
        ),
    ]
